set -g default-terminal "xterm-256color"
set -g xterm-keys on
set -sa terminal-overrides ",*:dim=\\E[2m"

# Change prefix key
set-option -g prefix M-m
bind-key M-m send-prefix
unbind-key C-b

# Don't pause waiting for control chars after an Esc
set -s escape-time 0

# Navigating through panes
unbind-key Left
unbind-key Up
unbind-key Right
unbind-key Down
unbind-key j
unbind-key k
unbind-key h
unbind-key l
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set-window-option -g mode-keys vi
bind P paste
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Spawn new window
unbind-key c
bind-key Enter new-window

# Detach
bind-key 4 detach

# Navigating through windows
unbind M-h
unbind M-l
bind-key M-h select-window -p
bind-key M-l select-window -n
bind-key g command-prompt "select-window -t '%%'"

# Killing things
bind-key q confirm-before -p '[#H] Kill pane at #{pane_current_path}?' kill-pane
bind-key Q confirm-before -p '[#H] Kill window #{window_id} with #{window_panes} panes?' kill-window

# Splitting vertically/horizontally.
# The newly split pane is opened in the directory of the current pane.
unbind-key %
unbind-key '"'
bind-key v split-window -v -c '#{pane_current_path}'
bind-key V split-window -vf -c '#{pane_current_path}'
bind-key b split-window -h -c '#{pane_current_path}'
bind-key B split-window -hf -c '#{pane_current_path}'

set -g history-limit 100000

# Count things from 1 rather than 0
set-option -g base-index 1
set-option -g pane-base-index 1

bind-key r command-prompt -p "[#H] rename-window" -I '#W' "rename-window '%1'"

# Tweaks to the status line
set-option -g status-left "#H"
set-option -g status-left-length 20
set-option -g status-right "[#{session_name}]"
set-option -g status-justify centre
set-option -g status-position top

# Reload this config file
bind R source-file /usr/local/etc/tmux.conf\; \
    display-message "[#H] tmux.conf is reloaded"

# Resizing the panes
bind-key -r H resize-pane -L
bind-key -r J resize-pane -D
bind-key -r K resize-pane -U
bind-key -r L resize-pane -R

set-option -g repeat-time 300

bind-key + command-prompt
set-option -g pane-active-border-style "bg=colour130,fg=black"
set-option -g pane-border-lines single
set-option -g status-style "bg=colour130,fg=gray90"
set-option -g clock-mode-colour colour130

unbind-key d

bind-key Left swap-pane -U
bind-key Right swap-pane -D
bind-key Up swap-pane -U
bind-key Down swap-pane -D
unbind-key z
bind-key m resize-pane -Z

bind-key / command-prompt -p "[#H] man" "split-window 'exec man %%'"

# Custom aliases (start at index 100 just to be sure)
set command-alias[100] aro='attach -f read-only'	# Attach read-only
